language: node_js
node_js: "lts/*"
install: yarn
script: yarn build
branches:
  only: 
  - master
  - dev
jobs:
  include:
    -
      if: branch = master
      env: REACT_APP_API=https://innovic.azurewebsites.net/api
    -
      if: branch = dev
      env: REACT_APP_API=https://dev-innovic-api.azurewebsites.net/api
deploy:
  - provider: pages
    edge:
      branch: pages-ivar-set
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build
    on:
      branch: master
  - provider: surge
    project: ./build/
    domain: early-crush.surge.sh  
    skip_cleanup: true
    on:
      branch: dev