language: node_js
node_js: "lts/*"
install: yarn
script: yarn build
env:
  - REACT_APP_API=http://innovic.azurewebsites.net/api
jobs:
  include:
      if: branch = dev
      env: REACT_APP_API=http://dev-innovic-api.azurewebsites.net/api
deploy:
  - provider: pages
    edge:
      branch: pages-ivar-set
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: build
    on:
      branch: master
  - provider: surge
    project: ./build/
    domain: early-crush.surge.sh  
    skip_cleanup: true
    on:
      branch: dev