language: node_js
node_js:
  - "iojs"
  - "7"
install: yarn
script: yarn run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: build